language: python
dist: xenial
python:
  - '3.7'
install:
  - pip install -r requirements.txt
script:
  - python -m pytest -v
deploy:
  provider: pypi
  user: michalfilippi
  password:
    secure: lFAcyGchcdJx+ApCdzIlqdKMnZp9G41/X0L5sPNqpaZvQwNL0vMpvixsA2wIf6M3tjoaWX0cc8zr9Ar/Xm+6XC9CqeiyJvGbHvCf9xYiOI7SSZS+C4YD7AwngrTQQTVekkVq69nZzzPZBOqYrkktZNgadf4vCLsdkinXeCHIyeETtK5tQ++Wpys6d5KsJ6uJ9GtcfQgG1Vchw0c5EuiSbyGjE5NP+72Ej9+f9o++XfSGQfXpBsewpOJpdGTbEjyIUN48LwHw0BnnDUa6wqQx0wMf7LjarTXjIYIaBDzVHXZgraq58j3XSjfUpYMrIO0HuFOSshGczG6xf66ltPhGx8OJ0oV2yGv8XWxn2FvoU/n/hGbLUILUOThTm7CeyN0FPLtpl6iHLH/kulWnRS7TUOI4iiNOZIML5AllIJ+7yiN5qWY2GAWquqN42bhNDDPXZTKr3hQj1+zGz1uPF2RqMw2HWAbfv6E7T+Gl3VrOo24imhIKEuePUF3NedV6yY8+8yGV6XldxTmumR+vzz3p5+YIDLsTVJ2ZotXNCrryQ3K8KeNDAGbZbRYfVNjbrY3cts9HljnVsXGw4GolpORNrH4kOPgPOZiQV2Gi3Ie+U/NjR8HofPt+6vKMkAxN1naL4l84EXVjCyMwxJyorKznNjKhecffq52UmYnoC0VZJtw=
  on:
    tags: true
